
package view;

import dao.DaoStudentUse;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import model.Student;

/**
 *
 * @author tokyo
 */
public class Update extends javax.swing.JFrame {
    int xMouse, yMouse;
    private static Update instance = null;
    ListW listwindow =  ListW.getInstance();
    private int selectedRow;

    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        configureKeyBindings();
        jTable1.setModel(listwindow.getTableModel());
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
        Class<?> columnClass = jTable1.getColumnClass(i);
        jTable1.setDefaultEditor(columnClass, null);
        } 
        
       
    }
    
    public static Update getInstance() {
        if (instance == null) {
            instance = new Update();
        }
        return instance;
    }
    
    private void configureKeyBindings() {
        JRootPane rootPane = this.getRootPane();  // Obtener el JRootPane de la ventana
        rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "enterPressed");
        rootPane.getActionMap().put("enterPressed", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Aquí pones lo que quieres que suceda cuando se presiona Enter
                  DaoStudentUse studentDao = DaoStudentUse.getInstance();

        // Obtiene la fila seleccionada
        int selectedRow = jTable1.getSelectedRow();
        
        // Verifica que una fila esté seleccionada
        if (selectedRow != -1) {
            // Obtiene el ID de la fila seleccionada
            int idToUpdate = (int) jTable1.getValueAt(selectedRow, jTable1.getColumnCount() - 1);

            // Encuentra el estudiante en el Dao
            Student studentById = studentDao.getStudentById(idToUpdate);
            if (studentById != null) {
                // Actualiza los datos del estudiante
                studentById.setName(nameTxt.getText());
                studentById.setDocumentId(idTxt.getText()); // Asegúrate de tener este método en tu clase Student

                // Actualiza el estudiante en el Dao
                studentDao.updateStudent(studentById);

                // Actualiza el archivo del estudiante
                studentDao.updateStudentFileExternally(studentById);

                // Actualiza el modelo de la tabla
                listwindow.dtm.setValueAt(nameTxt.getText() + " " + lastNameTxt.getText(), selectedRow, 0);
                listwindow.dtm.setValueAt(idTxt.getText(), selectedRow, 1); // Suponiendo que ID documento está en la columna 1

                System.out.println("Estudiante actualizado: " + studentById.getName());
            } else {
                System.out.println("Estudiante con ID " + idToUpdate + " no encontrado.");
            }
        } else {
            System.out.println("No se seleccionó ninguna fila.");
        }
                
            }
        });
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        updateBtn = new javax.swing.JPanel();
        updateBtnTxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nameLabel = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        addressLabel = new javax.swing.JLabel();
        addresTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        idTxt = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        idLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateTextField = new javax.swing.JFormattedTextField();
        jSeparator5 = new javax.swing.JSeparator();
        userLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        numLabel = new javax.swing.JLabel();
        numTextField = new javax.swing.JFormattedTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<>();
        numLabel1 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        seleccBtn1 = new javax.swing.JPanel();
        seleccBtnTxt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setDoubleBuffered(false);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cerrar-simbolo-de-boton-circular.png"))); // NOI18N
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/flechas-izquierda.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1094, 1094, 1094)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));

        title.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        title.setText("Actualizar contacto");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        updateBtn.setBackground(new java.awt.Color(0, 134, 190));

        updateBtnTxt.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        updateBtnTxt.setForeground(new java.awt.Color(255, 255, 255));
        updateBtnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateBtnTxt.setText("Actualizar");
        updateBtnTxt.setToolTipText("");
        updateBtnTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateBtnTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateBtnTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateBtnTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout updateBtnLayout = new javax.swing.GroupLayout(updateBtn);
        updateBtn.setLayout(updateBtnLayout);
        updateBtnLayout.setHorizontalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(updateBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(updateBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        updateBtnLayout.setVerticalGroup(
            updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(updateBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(updateBtnLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(updateBtnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 130, 40));

        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setDragEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 1100, 210));

        nameLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        nameLabel.setText("NOMBRE");
        bg.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 80, 20));

        nameTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nameTxt.setForeground(new java.awt.Color(204, 204, 204));
        nameTxt.setText("Ingrese el nombre ");
        nameTxt.setBorder(null);
        nameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameTxtMousePressed(evt);
            }
        });
        bg.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 170, 30));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 170, 20));

        addressLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        addressLabel.setText("DIRECCIÓN");
        bg.add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 390, -1, -1));

        addresTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        addresTxt.setForeground(new java.awt.Color(204, 204, 204));
        addresTxt.setText("Dirección");
        addresTxt.setBorder(null);
        addresTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addresTxtMousePressed(evt);
            }
        });
        bg.add(addresTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 170, 30));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 450, 160, 20));

        idTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        idTxt.setForeground(new java.awt.Color(204, 204, 204));
        idTxt.setText("Ingrese el numero");
        idTxt.setBorder(null);
        idTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idTxtMousePressed(evt);
            }
        });
        bg.add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 170, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setToolTipText("");
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 170, 20));

        idLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        idLabel.setText("DOCUMENTO ID");
        bg.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        dateLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        dateLabel.setText("FECHA DE NACIMIENTO");
        bg.add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        dateTextField.setBorder(null);
        dateTextField.setForeground(new java.awt.Color(204, 204, 204));
        dateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateTextField.setText("MM/DD/YY");
        dateTextField.setToolTipText("");
        dateTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        dateTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dateTextFieldMousePressed(evt);
            }
        });
        bg.add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 170, 30));

        jSeparator5.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 170, 20));

        userLabel7.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        userLabel7.setText("CONTACTO");
        bg.add(userLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor", "Estudiante" }));
        jComboBox1.setBorder(null);
        bg.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 160, 30));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 160, 20));

        lastNameLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lastNameLabel.setText("APELLIDOS");
        bg.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 90, -1));

        lastNameTxt.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lastNameTxt.setForeground(new java.awt.Color(204, 204, 204));
        lastNameTxt.setText("Ingrese el apellido");
        lastNameTxt.setBorder(null);
        lastNameTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lastNameTxtMousePressed(evt);
            }
        });
        bg.add(lastNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 170, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setToolTipText("");
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, 120, 20));

        numLabel.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        numLabel.setText("TIPO TL ");
        bg.add(numLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, -1, -1));

        numTextField.setBorder(null);
        numTextField.setForeground(new java.awt.Color(204, 204, 204));
        numTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##########"))));
        numTextField.setText("Ingrese N°");
        numTextField.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        numTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numTextFieldMousePressed(evt);
            }
        });
        bg.add(numTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 160, 30));

        jSeparator7.setForeground(new java.awt.Color(51, 51, 51));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 170, 20));

        jComboBox2.setEditable(true);
        jComboBox2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Móvil", "Telefono", "Oficina" }));
        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        bg.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 120, 30));

        numLabel1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        numLabel1.setText("NÚMERO TL");
        bg.add(numLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator8.setToolTipText("");
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 170, 20));

        seleccBtn1.setBackground(new java.awt.Color(0, 134, 190));

        seleccBtnTxt1.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        seleccBtnTxt1.setForeground(new java.awt.Color(255, 255, 255));
        seleccBtnTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccBtnTxt1.setText("Seleccionar");
        seleccBtnTxt1.setToolTipText("");
        seleccBtnTxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seleccBtnTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccBtnTxt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seleccBtnTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seleccBtnTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout seleccBtn1Layout = new javax.swing.GroupLayout(seleccBtn1);
        seleccBtn1.setLayout(seleccBtn1Layout);
        seleccBtn1Layout.setHorizontalGroup(
            seleccBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
            .addGroup(seleccBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seleccBtn1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(seleccBtnTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        seleccBtn1Layout.setVerticalGroup(
            seleccBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(seleccBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(seleccBtn1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(seleccBtnTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(seleccBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void updateBtnTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnTxtMouseEntered
        updateBtn.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_updateBtnTxtMouseEntered

    private void updateBtnTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnTxtMouseExited
        updateBtn.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_updateBtnTxtMouseExited

    private void nameTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTxtMousePressed
        // TODO add your handling code here:
        nameTxt.setText("");
        nameTxt.setForeground(Color.black);
    }//GEN-LAST:event_nameTxtMousePressed

    private void addresTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addresTxtMousePressed
        // TODO add your handling code here:
        addresTxt.setText("");
        addresTxt.setForeground(Color.black);
    }//GEN-LAST:event_addresTxtMousePressed

    private void idTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTxtMousePressed
        // TODO add your handling code here:
        idTxt.setText("");
        idTxt.setForeground(Color.black);
    }//GEN-LAST:event_idTxtMousePressed

    private void dateTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateTextFieldMousePressed
        // TODO add your handling code here:
        dateTextField.setText("");
        dateTextField.setForeground(Color.black);
    }//GEN-LAST:event_dateTextFieldMousePressed

    private void lastNameTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameTxtMousePressed
        // TODO add your handling code here:
        lastNameTxt.setText("");
        lastNameTxt.setForeground(Color.black);
    }//GEN-LAST:event_lastNameTxtMousePressed

    private void numTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numTextFieldMousePressed
        // TODO add your handling code here:
        numTextField.setText("");
        numTextField.setForeground(Color.black);
    }//GEN-LAST:event_numTextFieldMousePressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void seleccBtnTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccBtnTxt1MouseClicked
        // TODO add your handling code here:
        DaoStudentUse studentDao = DaoStudentUse.getInstance();
        selectedRow = jTable1.getSelectedRow()+1;
        
        if (selectedRow > studentDao.getsizeSt()){
         selectedRow--;
        }
        Student studentById = studentDao.getStudent(selectedRow );
        if (studentById != null) {
            System.out.println("Estudiante encontrado: " + studentById.getName() + " " + "fila " + selectedRow );
        } else {
            System.out.println("Estudiante " + (selectedRow) +" no encontrado" );
        }
        
        nameTxt.setText(studentById.getName());
        nameTxt.setForeground(Color.black);
        lastNameTxt.setText(studentById.getLastName());
        lastNameTxt.setForeground(Color.black);
        idTxt.setText(studentById.getDocumentId());
        idTxt.setForeground(Color.black);
        dateTextField.setText(studentById.getDate());
        dateTextField.setForeground(Color.black);
        numTextField.setText(studentById.getPhoneNumber());
        numTextField.setForeground(Color.black);
        addresTxt.setText(studentById.getAddres());
        addresTxt.setForeground(Color.black);
        jComboBox2.setSelectedItem(studentById.getTypePhone());
//        listwindow.dtm.setValueAt(studentById.getLastName(), fila, 0);
    }//GEN-LAST:event_seleccBtnTxt1MouseClicked

    private void seleccBtnTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccBtnTxt1MouseEntered
        // TODO add your handling code here:
        seleccBtn1.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_seleccBtnTxt1MouseEntered

    private void seleccBtnTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccBtnTxt1MouseExited
        // TODO add your handling code here:
        seleccBtn1.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_seleccBtnTxt1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Menu menu=Menu.getInstance();
        menu.setVisible(true);
        Update update = Update.getInstance();
        update.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void updateBtnTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnTxtMouseClicked
        // TODO add your handling code here:     
          DaoStudentUse studentDao = DaoStudentUse.getInstance();

        // Obtiene la fila seleccionada
        int selectedRow = jTable1.getSelectedRow();
        
        // Verifica que una fila esté seleccionada
        if (selectedRow != -1) {
            // Obtiene el ID de la fila seleccionada
            int idToUpdate = (int) jTable1.getValueAt(selectedRow, jTable1.getColumnCount() - 1);

            // Encuentra el estudiante en el Dao
            Student studentById = studentDao.getStudentById(idToUpdate);
            if (studentById != null) {
                // Actualiza los datos del estudiante
                studentById.setName(nameTxt.getText());
                studentById.setDocumentId(idTxt.getText()); // Asegúrate de tener este método en tu clase Student

                // Actualiza el estudiante en el Dao
                studentDao.updateStudent(studentById);

                // Actualiza el archivo del estudiante
                studentDao.updateStudentFileExternally(studentById);

                // Actualiza el modelo de la tabla
                listwindow.dtm.setValueAt(nameTxt.getText() + " " + lastNameTxt.getText(), selectedRow, 0);
                listwindow.dtm.setValueAt(idTxt.getText(), selectedRow, 1); // Suponiendo que ID documento está en la columna 1

                System.out.println("Estudiante actualizado: " + studentById.getName());
            } else {
                System.out.println("Estudiante con ID " + idToUpdate + " no encontrado.");
            }
        } else {
            System.out.println("No se seleccionó ninguna fila.");
        }  
  
        
    }//GEN-LAST:event_updateBtnTxtMouseClicked
     
    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresTxt;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JFormattedTextField dateTextField;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JPanel header;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel numLabel;
    private javax.swing.JLabel numLabel1;
    private javax.swing.JFormattedTextField numTextField;
    private javax.swing.JPanel seleccBtn1;
    private javax.swing.JLabel seleccBtnTxt1;
    private javax.swing.JLabel title;
    private javax.swing.JPanel updateBtn;
    private javax.swing.JLabel updateBtnTxt;
    private javax.swing.JLabel userLabel7;
    // End of variables declaration//GEN-END:variables
}
